Use bootctl to get default kernel and initrd
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/systemd-boot/default-settings b/systemd-boot/default-settings
--- a/systemd-boot/default-settings
+++ b/systemd-boot/default-settings
@@ -10,31 +10,20 @@
 # include common functions
 . "$PBL_INCLUDE/library"
 
-target=$(uname -m)
-
-case "$target" in
-  x86_64|i?86)
-    image=vmlinuz ;;
-  ppc*)
-    image=vmlinux ;;
-  s390*)
-    image=image ;;
-  armv*)
-    image=zImage ;;
-  aarch64|riscv64)
-    image=Image ;;
-  *)
-    echo "Architecture $target not supported."
-esac
-
 lib_get_cmdline_bls
 
-kernel=$(readlink -f "/boot/$image")
-initrd=$(readlink -f /boot/initrd)
-append=\"$(lib_shellquote "$cmdline")\"
+err=0
+if [ -x /usr/bin/bootctl ]; then
+  kernel=$(bootctl status | grep linux: | cut -d':' -f2 | tr -d ' ')
+  initrd=$(bootctl status | grep initrd: | cut -d':' -f2 | tr -d ' ')
+  append=\"$(lib_shellquote "$cmdline")\"
 
-echo "kernel=$kernel" > "$PBL_RESULT"
-echo "initrd=$initrd" >> "$PBL_RESULT"
-echo -n "append=$append" >> "$PBL_RESULT"
+  echo "kernel=$kernel" > "$PBL_RESULT"
+  echo "initrd=$initrd" >> "$PBL_RESULT"
+  echo -n "append=$append" >> "$PBL_RESULT"
+else
+  echo "bootctl: command not found"
+  err=1
+fi
 
-exit 0
+exit $err
