Use sdbootutil to set default entry
Both systemd-boot and grub2-bls uses the boot loader specification, but
only systemd-boot truly uses the boot loader interface (BLI).  This
interface describes a set of EFI variables used to mark elements like
the default entry or the menu timeout.

sdbootutil has now two new commands inherited from bootctl, set-default
and set-timeout.  Those commands will use the corresponding
configuration file (loader.conf for systemd-boot, grubenv for grub2) for
cases where the EFI variables are not present or the BLI is not
followed.

This commit use the set-default commands from sdbootutil instead the one
from bootctl for the "default" pbl command.

Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/systemd-boot/default b/systemd-boot/default
--- a/systemd-boot/default
+++ b/systemd-boot/default
@@ -8,10 +8,10 @@
 #
 
 err=0
-if [ -x /usr/bin/bootctl ] ; then
-  ( set -x ; bootctl set-default "$1" ) || err=1
+if [ -x /usr/bin/sdbootutil ] ; then
+  ( set -x ; sdbootutil set-default "$1" ) || err=1
 else
-  echo "bootctl: command not found"
+  echo "sdbootutil: command not found"
   err=1
 fi
 
