Use sdbootutil to install the bootloader
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/systemd-boot/install b/systemd-boot/install
--- a/systemd-boot/install
+++ b/systemd-boot/install
@@ -8,10 +8,10 @@
 #
 
 err=0
-if [ -x /usr/bin/bootctl ] ; then
-  ( set -x ; bootctl --make-machine-id-directory=yes install ) || err=1
+if [ -x /usr/bin/sdbootutil ] ; then
+  sdbootutil install || err=1
 else
-  echo "bootctl: command not found"
+  echo "sdbootutil: command not found"
   err=1
 fi
 
