rework del-option command

diff --git a/grub2/del-option b/grub2/del-option
--- a/grub2/del-option
+++ b/grub2/del-option
@@ -1,4 +1,11 @@
-#! /usr/bin/perl
+#! /usr/bin/sh
+
+# Settings from /etc/sysconfig/filename are available as environment vars
+# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
+#
+# Not all files are parsed, current list is:
+#   bootloader, language
+#
 
 # usage: del-option OPTION
 #
@@ -6,50 +13,69 @@
 #
 # OPTION is either of the form 'key=value' or 'key="value"' or just 'key'.
 
-use strict;
+if [ -e /etc/default/grub ] ; then
+  . /etc/default/grub
+  if [ -z "$GRUB_CMDLINE_LINUX_DEFAULT" ] ; then
+    echo "Warning: GRUB_CMDLINE_LINUX_DEFAULT is empty"
+  fi
+else
+  echo "/etc/default/grub missing"
+  exit 1
+fi
 
-my $file = "/etc/default/grub";
+cmd="$GRUB_CMDLINE_LINUX_DEFAULT"
 
-my $opt = shift;
+opt="$1"
 
-$opt =~ s/=("?).*//;
+echo "cmdline (old): $cmd"
 
-exit 1 if $opt eq "";
+ifs_orig="$IFS" IFS=
 
-open my $f, $file or die "$file: $!\n";
-my @lines = (<$f>);
-close $f;
+nl=$'\n'
+q=0
+n=
+while read -r -n 1 foo ; do
+  if [ "$q" = 0 ] ; then
+    [ "$foo" = '"' ] && q=1
+  else
+    [ "$foo" = '"' ] && q=0
+  fi
+  [ "$foo" = " " -a "$q" = 0 ] && foo="$nl"
+  n="$n$foo"
+done <<XXX
+$cmd
+XXX
 
-my $changed = 0;
+IFS="$nl"
 
-for (@lines) {
-  if(/^(GRUB_CMDLINE_LINUX_DEFAULT)=(.*)/) {
-    $changed = 1;
-    my $key = $1;
-    my $val = $2;
+changed=
+newcmd=
+for i in $n ; do
+  match="${i#"$opt"}"
+  if [ "$match" != "$i" -a \( -z "$match" -o "${match:0:1}" = "=" \) ] ; then
+    changed=1
+  else
+    newcmd="$newcmd $i"
+  fi
+done
 
-    $val =~ s/(^"\s*|\s*"\s*$)//g;
+IFS="$ifs_orig"
 
-    $val =~ s/(^|\s)$opt=(\\"[^"]*\\"\s*)/ / or
-    $val =~ s/(^|\s)$opt((\s|$)|(=\S*\s*))/ /;
+newcmd=${newcmd# }
 
-    $val =~ s/^\s+|\s+$//g;
+if [ -z "$changed" ] ; then
+  echo "cmdline not updated"
+  exit 0
+fi
 
-    $_ = "$key=\"$val\"\n";
-  }
+echo "cmdline (new): $newcmd"
+
+newcmd=${newcmd//\\/\\\\\\\\}
+newcmd=${newcmd//\"/\\\\\"}
+
+sed -i -e "/^GRUB_CMDLINE_LINUX_DEFAULT=/c GRUB_CMDLINE_LINUX_DEFAULT=\"$newcmd\"" /etc/default/grub || {
+  echo "/etc/default/grub: failed to update config file"
+  exit 1
 }
 
-exit 0 unless $changed;
-
-my $f;
-
-if(!(
-  open $f, ">$file.pblnew" and
-  print $f @lines and
-  close $f and
-  rename "$file.pblnew", $file
-)) {
-  unlink "$file.pblnew";
-  die "$file: failed to update config file\n"
-}
-
+exit 0
